name: Check Links

on:
  push:
    branches: [ master ]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master branch
        uses: actions/checkout@v2

      - name: check links
        uses: lycheeverse/lychee-action@v1.0.9
        with:
          args: --verbose --no-progress README.md